# Generated by Django 3.1.2 on 2020-12-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lonliness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, verbose_name='名前')),
                ('who_is', models.CharField(max_length=63, verbose_name='自己紹介')),
                ('content', models.CharField(max_length=255, verbose_name='さみしさ')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_char', models.IntegerField(verbose_name='リアクション')),
                ('lonliness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='gravitation.lonliness', verbose_name='さみしさ')),
            ],
        ),
    ]
